-- MySQL Script generated by MySQL Workbench
-- Fri Jun  2 14:57:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema camden_dairy_farm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `camden_dairy_farm` ;

-- -----------------------------------------------------
-- Schema camden_dairy_farm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `camden_dairy_farm` DEFAULT CHARACTER SET utf8 ;
USE `camden_dairy_farm` ;

-- -----------------------------------------------------
-- Table `camden_dairy_farm`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camden_dairy_farm`.`Payment` (
  `payment_id` CHAR(36) NOT NULL,
  `paymentDate` DATE NOT NULL,
  `total_price` DECIMAL(6,2) NOT NULL,
  `quotationDiscount` TINYINT NOT NULL,
  `payment_method` TINYINT NOT NULL,
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camden_dairy_farm`.`rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camden_dairy_farm`.`rate` (
  `rate_code` CHAR(36) NOT NULL,
  `quantity` INT NOT NULL,
  `discount_percentage` TINYINT NOT NULL,
  PRIMARY KEY (`rate_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camden_dairy_farm`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camden_dairy_farm`.`Address` (
  `address_id` CHAR(36) NOT NULL,
  `street_name` VARCHAR(50) NOT NULL,
  `street_number` VARCHAR(10) NOT NULL,
  `neighborhood` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camden_dairy_farm`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camden_dairy_farm`.`Client` (
  `client_id` CHAR(36) NOT NULL,
  `fullname` VARCHAR(50) NOT NULL,
  `phone_number` CHAR(13) NOT NULL,
  `address_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`client_id`),
  INDEX `fk_client_address_id` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `camden_dairy_farm`.`Address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camden_dairy_farm`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camden_dairy_farm`.`Order` (
  `order_id` CHAR(36) NOT NULL,
  `value_of_deposit` DECIMAL(6,2) NOT NULL,
  `requestDate` DATE NOT NULL,
  `validity` DATE NOT NULL,
  `payment_id` CHAR(36) NOT NULL,
  `rate_code` CHAR(36) NOT NULL,
  `client_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_payment_id` (`payment_id` ASC) VISIBLE,
  INDEX `fk_order_rate_id` (`rate_code` ASC) VISIBLE,
  INDEX `fk_order_Client_id` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Payment`
    FOREIGN KEY (`payment_id`)
    REFERENCES `camden_dairy_farm`.`Payment` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_rate1`
    FOREIGN KEY (`rate_code`)
    REFERENCES `camden_dairy_farm`.`rate` (`rate_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `camden_dairy_farm`.`Client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camden_dairy_farm`.`Address_of_shipping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camden_dairy_farm`.`Address_of_shipping` (
  `Address_address_id` CHAR(36) NOT NULL,
  `Order_order_id` CHAR(36) NOT NULL,
  `deliveryDate` DATE NULL,
  PRIMARY KEY (`Address_address_id`, `Order_order_id`),
  INDEX `fk_Address_order_order_id` (`Order_order_id` ASC) VISIBLE,
  INDEX `fk_address_order_address_id` (`Address_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Address_has_Order_Address1`
    FOREIGN KEY (`Address_address_id`)
    REFERENCES `camden_dairy_farm`.`Address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Address_has_Order_Order1`
    FOREIGN KEY (`Order_order_id`)
    REFERENCES `camden_dairy_farm`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camden_dairy_farm`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camden_dairy_farm`.`Product` (
  `product_id` CHAR(36) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `price_of_sale` DECIMAL(5,2) NOT NULL,
  `stock` SMALLINT NOT NULL,
  `expiration_date` DATE NOT NULL,
  `production_date` DATE NOT NULL,
  `production_cost` DECIMAL(6,2) NOT NULL,
  `comments` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camden_dairy_farm`.`order_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camden_dairy_farm`.`order_product` (
  `order_id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `quantity` SMALLINT NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_order_product_product_id` (`product_id` ASC) VISIBLE,
  INDEX `fk_order_product_order_id` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_has_Product_Order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `camden_dairy_farm`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Product_Product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `camden_dairy_farm`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camden_dairy_farm`.`rent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camden_dairy_farm`.`rent` (
  `rent_id` CHAR(36) NOT NULL,
  `rentalFee` DECIMAL(6,2) NOT NULL,
  `address_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`rent_id`),
  INDEX `fk_rent_address_id` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_rent_Address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `camden_dairy_farm`.`Address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camden_dairy_farm`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camden_dairy_farm`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
